/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ecommerce.mobile

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class EcommerceMobilePlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'ecommerce.mobile.greeting'")
            }
        }
    }
}
